from pathlib import Path

# Main paths
DATA_ROOT = Path("data_challenge_netmob_2026_V-2026-06-15/data")
MOBILITY_FILE = DATA_ROOT / "mobility_data/2026-03-12.csv"

AUX_DIR = DATA_ROOT / "auxiliar_data"
GTFS_ROOT = DATA_ROOT / "GTFS_data"
GTFS_FEED_DIRS = [GTFS_ROOT / "TransNit_20260320", GTFS_ROOT / "TransOceanico_20260315"]

IBGE_BAIRROS = Path("ibge/RJ_bairros_CD2022.gpkg")

OUTPUT_ROOT = Path("cluster_analysis/processed_data")
OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

GTFS_PROCESSED_DIR = OUTPUT_ROOT / "gtfs"
OSM_PROCESSED_DIR = OUTPUT_ROOT / "osm"
POINTS_PROCESSED_DIR = OUTPUT_ROOT / "points"
CLUSTERS_PROCESSED_DIR = OUTPUT_ROOT / "clusters"

IMAGES_DIR = Path("cluster_analysis/processed_data/gifs")

for folder in [GTFS_PROCESSED_DIR, OSM_PROCESSED_DIR, POINTS_PROCESSED_DIR, CLUSTERS_PROCESSED_DIR, IMAGES_DIR]:
    folder.mkdir(parents=True, exist_ok=True)

# Focus area and time
FOCUS_BAIRRO = "CENTRO"
DATE_LABEL = "2026-03-12"

# Use a slightly wider preprocessing window than the animation window
# so rolling speeds have a context before/after the GIF period
PREPROCESS_START_TIME = "2026-03-12 07:20:00"
PREPROCESS_END_TIME = "2026-03-12 08:40:00"

ANIMATION_START_TIME = "2026-03-12 07:30:00"
ANIMATION_END_TIME = "2026-03-12 08:30:00"

FRAME_FREQ = "15s"

CHUNK_SIZE = 200_000

METRIC_CRS = "EPSG:32723" # UTM 23S Projected Coordinate System used in Brazil, good for Niterói
NETWORK_TYPE = "drive"

# Output files
PREPARED_GTFS_STOPS = GTFS_PROCESSED_DIR / "gtfs_stops.gpkg"
PREPARED_GTFS_TERMINALS = GTFS_PROCESSED_DIR / "gtfs_terminals.gpkg"
PREPARED_GTFS_SHAPES = GTFS_PROCESSED_DIR / "gtfs_shapes.gpkg"
PREPARED_GTFS_ROUTES = GTFS_PROCESSED_DIR / "gtfs_routes.csv"
PREPARED_GTFS_TRIPS = GTFS_PROCESSED_DIR / "gtfs_trips.csv"
PREPARED_GTFS_ROUTE_SHAPES = GTFS_PROCESSED_DIR / "gtfs_route_shape_lookup.csv"

OSM_EDGES_FILE = OSM_PROCESSED_DIR / f"{FOCUS_BAIRRO.lower()}_osm_edges.gpkg"

SNAPPED_POINTS_FILE = (POINTS_PROCESSED_DIR / f"{DATE_LABEL}_{FOCUS_BAIRRO.lower()}_snapped_points.parquet")
ENRICHED_POINTS_FILE = (POINTS_PROCESSED_DIR / f"{DATE_LABEL}_{FOCUS_BAIRRO.lower()}_snapped_points_gtfs.parquet")
SLOW_SCORE_POINTS_FILE = (POINTS_PROCESSED_DIR / f"{DATE_LABEL}_{FOCUS_BAIRRO.lower()}_slow_score_points.parquet")
CLUSTER_FRAMES_FILE = (CLUSTERS_PROCESSED_DIR / f"{DATE_LABEL}_{FOCUS_BAIRRO.lower()}_cluster_frames.csv")
CLUSTER_POINTS_FILE = (CLUSTERS_PROCESSED_DIR / f"{DATE_LABEL}_{FOCUS_BAIRRO.lower()}_cluster_points.csv")
TRACKED_EVENTS_FILE = (CLUSTERS_PROCESSED_DIR / f"{DATE_LABEL}_{FOCUS_BAIRRO.lower()}_tracked_cluster_events.csv")
EVENT_SUMMARY_FILE = (CLUSTERS_PROCESSED_DIR / f"{DATE_LABEL}_{FOCUS_BAIRRO.lower()}_event_summary.csv") 
OUTPUT_GIF = (IMAGES_DIR / f"{DATE_LABEL}_{FOCUS_BAIRRO.lower()}_snapped_cluster_animation2.gif")

# Speed/slow-score settings
ROLLING_SPEED_WINDOW = 4
ROLLING_SPEED_METHOD = "mean"

FREE_FLOW_QUANTILE = 0.85
STOPPED_THRESHOLD_KMH = 1.0
MAX_SPEED_KMH = 120
MIN_TIME_DIFF_SECONDS = 5
MAX_TIME_DIFF_SECONDS = 180

"""
# STRICT DETECTION

CLUSTER_SLOW_SCORE_THRESHOLD = 0.60
DBSCAN_EPS_METERS = 45
DBSCAN_MIN_SAMPLES = 4
TRACK_MAX_CENTROID_DISTANCE_M = 80

NEAR_STOP_METERS = 45
NEAR_TERMINAL_METERS = 100

ROAD_MIN_UNIQUE_ROUTES = 4
ROAD_MIN_LINE_ENTROPY = 0.70
ROAD_MAX_DWELL_FRACTION = 0.25
ROAD_MAX_TERMINAL_FRACTION = 0.25
ROAD_MIN_UNIQUE_BUSES = 5
ROAD_MIN_DURATION_MINUTES = 3.0

DWELL_EVENT_MIN_DWELL_FRACTION = 0.70
TERMINAL_EVENT_MIN_TERMINAL_FRACTION = 0.70

STATIONARY_MAX_SPEED_M_PER_MIN = 6
STATIONARY_MAX_DISPLACEMENT_M = 50

RUBBER_MIN_DURATION_MINUTES = 4.0
RUBBER_MIN_DISPLACEMENT_M = 35
RUBBER_MAX_SPEED_M_PER_MIN = 25
RUBBER_MIN_MAX_BUSES = 6
RUBBER_MIN_MAX_LINES = 4

FRAGMENT_MAX_DURATION_MINUTES = 2.0
FRAGMENT_MIN_SPEED_M_PER_MIN = 35
"""

"""
# MEDIUM DETECTION

CLUSTER_SLOW_SCORE_THRESHOLD = 0.52
DBSCAN_EPS_METERS = 50
DBSCAN_MIN_SAMPLES = 3
TRACK_MAX_CENTROID_DISTANCE_M = 100

NEAR_STOP_METERS = 35
NEAR_TERMINAL_METERS = 75

ROAD_MIN_UNIQUE_ROUTES = 3
ROAD_MIN_LINE_ENTROPY = 0.55
ROAD_MAX_DWELL_FRACTION = 0.35
ROAD_MAX_TERMINAL_FRACTION = 0.35
ROAD_MIN_UNIQUE_BUSES = 4
ROAD_MIN_DURATION_MINUTES = 2.0

DWELL_EVENT_MIN_DWELL_FRACTION = 0.65
TERMINAL_EVENT_MIN_TERMINAL_FRACTION = 0.65

STATIONARY_MAX_SPEED_M_PER_MIN = 8
STATIONARY_MAX_DISPLACEMENT_M = 60

RUBBER_MIN_DURATION_MINUTES = 3.0
RUBBER_MIN_DISPLACEMENT_M = 25
RUBBER_MAX_SPEED_M_PER_MIN = 35
RUBBER_MIN_MAX_BUSES = 5
RUBBER_MIN_MAX_LINES = 3

FRAGMENT_MAX_DURATION_MINUTES = 2.0
FRAGMENT_MIN_SPEED_M_PER_MIN = 40
"""

# RELAXED DETECTION

CLUSTER_SLOW_SCORE_THRESHOLD = 0.48
DBSCAN_EPS_METERS = 55
DBSCAN_MIN_SAMPLES = 3
TRACK_MAX_CENTROID_DISTANCE_M = 120

NEAR_STOP_METERS = 25
NEAR_TERMINAL_METERS = 60

ROAD_MIN_UNIQUE_ROUTES = 2
ROAD_MIN_LINE_ENTROPY = 0.45
ROAD_MAX_DWELL_FRACTION = 0.45
ROAD_MAX_TERMINAL_FRACTION = 0.50
ROAD_MIN_UNIQUE_BUSES = 3
ROAD_MIN_DURATION_MINUTES = 1.0

DWELL_EVENT_MIN_DWELL_FRACTION = 0.60
TERMINAL_EVENT_MIN_TERMINAL_FRACTION = 0.60

STATIONARY_MAX_SPEED_M_PER_MIN = 10
STATIONARY_MAX_DISPLACEMENT_M = 75

RUBBER_MIN_DURATION_MINUTES = 2.0
RUBBER_MIN_DISPLACEMENT_M = 20
RUBBER_MAX_SPEED_M_PER_MIN = 45
RUBBER_MIN_MAX_BUSES = 4
RUBBER_MIN_MAX_LINES = 2

FRAGMENT_MAX_DURATION_MINUTES = 1.5
FRAGMENT_MIN_SPEED_M_PER_MIN = 50

# Clustering settings
CLUSTER_HULL_BUFFER_METERS = 12

# Animation settings
CMAP_NAME = "inferno"

POINT_SIZE = 24
POINT_ALPHA = 0.9

SHOW_REGULAR_STOPS = True
SHOW_TERMINALS = True
SHOW_CLUSTER_LABELS = True

REGULAR_STOP_SIZE = 12
REGULAR_STOP_COLOR = "gray"
REGULAR_STOP_ALPHA = 0.75

TERMINAL_STOP_SIZE = 100
TERMINAL_STOP_COLOR = "red"
TERMINAL_STOP_ALPHA = 0.95